### ISSUE TITLE
bitcoin.payments is not defined

### ISSUE THREAD

**Issue by amyrprv** [novalabio/react-native-bitcoinjs-lib#1]
I want to get Address, public key and private key but `bitcoin.payments` function is not defined.

**Comment by achilovbakhrom** [comment]
Hi,
I have same issue and I want to copy `bitcoin.payment` from bitcoinjs-lib

**Comment by scalalang2** [comment]
Same as me.

**Comment by scalalang2** [comment]
I have found another library that added payment package.
https://github.com/viettranx/react-native-bitcoinjs-lib/commits/master

Fix package.json as below.
You can now use it payments function.

```json
{
   "dependencies": {
       "react-native-bitcoinjs-lib": "git+https://github.com/viettranx/react-native-bitcoinjs-lib.git",
   }
}
```
